### PR TITLE
finished project layout

### PR DESCRIPTION
**Pull request by Marwen-Brini**
-implemented project layout

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work on this project. You made quite impressive progress. Proper use of bootstrap classes and semantic HTML.
There's still a lot we need to fix concerning the PR.
- [ ] You currently only have the footer content of the page. The three columns and content are lacking. This is a clone of the News week's website. Your page should look exactly like that.
Below is how the columns are supposed to appear on different screens.
#### Note
- [ ] I have only provided you with the column titles. You need to add the content. Refer to the original [website](https://web.archive.org/web/20210120125445/https://www.newsweek.com/)
<table>
    <thead>
        <tr>
            <th colspan="3">Desktop</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>FEATURED STORIES</td>
            <td>TOP STORY</td>
            <td>THE DEBATE</td>
        </tr>
        <tr>
            <td>SPONSORED INSIGHT</td>
            <td>MY TURN</td>
            <td>OPINION</td>
        </tr>
        <tr>
            <td></td>
            <td>CULTURE & TRAVEL</td>
            <td>SPONSORED INSIGHT</td>
        </tr>
        <tr>
            <td></td>
            <td>MORE STORIES</td>
            <td>FREE SIGN UP</td>
        </tr>
        <tr>
            <td></td>
            <td>LATEST NEWS</td>
            <td>SPONSORED INSIGHT</td>
        </tr>
    </tbody>
</table>



<table>
    <thead>
        <tr>
            <th colspan="2">Tablet</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>FEATURED STORIES</td>
            <td>TOP STORY</td>
        </tr>
        <tr>
            <td>SPONSORED INSIGHT</td>
            <td>MY TURN</td>
        </tr>
        <tr>
            <td></td>
            <td>CULTURE & TRAVEL</td>
        </tr>
        <tr>
            <td></td>
            <td>MORE STORIES</td>
        </tr>
        <tr>
            <td></td>
            <td>LATEST NEWS</td>
        </tr>
        <tr>
            <td align="center" colspan="2">THE DEBATE</th>
        </tr>
        <tr>
            <td align="center" colspan="2">OPINION</th>
        </tr>
        <tr>
            <td align="center" colspan="2">SPONSORED INSIGHT</th>
        </tr>
        <tr>
            <td align="center" colspan="2">FREE SIGN UP</th>
        </tr>
        <tr>
            <td align="center" colspan="2">SPONSORED INSIGHT</th>
        </tr>
    </tbody>
</table>

<table>
    <thead>
        <tr>
            <th>Mobile</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>TOP STORY</th>
        </tr>
        <tr>
            <td>FEATURED STORIES</th>
        </tr>
        <tr>
            <td>THE DEBATE</th>
        </tr>
        <tr>
            <td>OPINION</th>
        </tr>
        <tr>
            <td>SPONSORED INSIGHT</th>
        </tr>
        <tr>
            <td>MORE STORIES</th>
        </tr>
        <tr>
            <td>LATEST NEWS</th>
        </tr>
        <tr>
            <td>MY TURN</th>
        </tr>
        <tr>
            <td>CULTURE & TRAVEL</th>
        </tr>
        <tr>
            <td>SPONSORED INSIGHT</th>
        </tr>
        <tr>
            <td>FREE SIGN UP</th>
        </tr>
        <tr>
            <td>SPONSORED INSIGHT</th>
        </tr>
    </tbody>
</table>
- [ ] The footer links should be aligned horizontally not vertically. Please fix that too.

### Martin Afani

**Comment by Marwen-Brini** [comment]
@whiz25 good morning the content is already there it's just that i forgot to change github pages from the first branch to the second, could you check again?

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Marwen-Brini 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed .

##

 - [ ] Kindly work on suggested changes
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @Marwen-Brini :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
